### ISSUE TITLE
notify fails when run the first time.

### ISSUE THREAD

**Issue by lowks** [lambdalisue/notify#2]
Notify fails at the keyring stage. 

```
Traceback (most recent call last):
  File "/home/lowks/virtualenvs/cdnpython/bin/notify", line 9, in <module>
    load_entry_point('notify==0.3.0', 'console_scripts', 'notify')()
  File "/home/lowks/virtualenvs/cdnpython/local/lib/python2.7/site-packages/notify/console.py", line 17, in main
    config = create_default_config()
  File "/home/lowks/virtualenvs/cdnpython/local/lib/python2.7/site-packages/notify/conf.py", line 114, in create_default_config
    setup_wizard(config)
  File "/home/lowks/virtualenvs/cdnpython/local/lib/python2.7/site-packages/notify/wizard.py", line 125, in setup_wizard
    keyring.set_password('notify', username, password)
  File "/home/lowks/virtualenvs/cdnpython/local/lib/python2.7/site-packages/notify/utils/plaintext_keyring.py", line 31, in set_password
    fo = open(self.filename, 'wb')
IOError: [Errno 2] No such file or directory: '/home/lowks/.config/notify/notify.keyring'
```

Perhaps better to catch it and show and error message ?

**Comment by lambdalisue** [comment]
Totally true. Thanks. I'll fix it soon

**Comment by lambdalisue** [comment]
Should be fixed from https://github.com/lambdalisue/notify/commit/6946a76982ee9108e5ecb7bf169151bdc1c8d772

**Comment by lowks** [comment]
I think it still needs a bit of love: https://github.com/lambdalisue/notify/pull/4

**Comment by lowks** [comment]
After the fix everything works well.
